spring:
    application:
        name: personal-blog-java
    liquibase:
        change-log: db/changelog/db.changelog-master.xml
    datasource:
        url: jdbc:postgresql://localhost:5432/blog
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver


